### ISSUE TITLE
RHEL yum updateinfo example not working due to host not entitled

### ISSUE THREAD

**Issue by jaryan-rh** [openshift-instruqt/instruqt#166]
In which track did this bug occur?

Understanding Subsystems / Understanding registries

what is the url for the track?
https://developers.redhat.com/courses/subsystems/registries

At what step of the track did this happen?

Evaluating Trust - Images and Registry Servers

```podman run -it registry.access.redhat.com/ubi7/ubi:7.6-73 yum updateinfo security```

Describe the bug
Running on RHEL and inside CRC, this doesn't appear to be working as expected.  Perhaps the certificate is not being mapped into the terminal the container is running in properly?

Logs or error messages
```
podman run -it registry.access.redhat.com/ubi7/ubi:7.6-73 yum updateinfo security
```
Expected behavior
Similar output to the following
```
RHSA-2019:0679 Important/Sec. libssh2-1.4.3-12.el7_6.2.x86_64
RHSA-2019:0710 Important/Sec. python-2.7.5-77.el7_6.x86_64
RHSA-2019:0710 Important/Sec. python-libs-2.7.5-77.el7_6.x86_64
```
Screenshots
See code copy and pase above

Desktop (please complete the following information):

OS: MacOS 12.6
Browser Chrome
Version 107.0.5304.87

Additional context

**Comment by cedricclyburn** [comment]
Hello @jaryan-rh! Thanks for bringing up this issue, I believe it's because our RHEL VM doesn't have an active subscription. Running it on RHEL with an active subscription outputs similar to the expected behavior that the lab describes, going to close for now.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/54345140/210902703-c261c7a1-339d-478a-872d-ccfbc8aebc7e.png">
