### ISSUE TITLE
CRC update - OpenShift 4.10

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#88]
- [x] extract latest CRC VM image
- [x] Build a new image (using the latest CRC)
- [x] Automate the rollout process, or provide a migration guide for content owners
- [ ] Optimize the image startup time
- [ ] Address SSL issues (avoid self-signed certs? Use zeroSSL?) #42
- [ ] remove CRC warning banner

Check these issues and update as needed:

- https://github.com/openshift-instruqt/instruqt/issues/13
- https://github.com/openshift-instruqt/instruqt/issues/14
- https://github.com/openshift-instruqt/instruqt/issues/15
- https://github.com/openshift-instruqt/instruqt/issues/16
- https://github.com/openshift-instruqt/instruqt/issues/62
- https://github.com/openshift-instruqt/instruqt/issues/64

**Comment by blues-man** [comment]
@ryanj the CRC 4.10 Image works, in order to update tracks we need to update:

- [config.yml](https://github.com/openshift-instruqt/instruqt/blob/master/examples/getting-started-4-10/config.yml#L4): 
 ```yaml
  image: openshift-instruqt/crc-4-10-latest
  machine_type: n1-highmem-4
```
- [setup-crc](https://github.com/openshift-instruqt/instruqt/blob/master/examples/getting-started-4-10/track_scripts/setup-crc): removed from the script pullscrets and user credentials (hardcoded in the image)
- [assignment.md|track.yml](https://raw.githubusercontent.com/openshift-instruqt/instruqt/master/examples/getting-started-4-10/01-1explore-cli/assignment.md):  Update the Web Console url due to a new hostname `crc-gh9wd-master-0` for the CRC image
```yaml
- title: Web Console
  type: website
  url: https://console-openshift-console.crc-gh9wd-master-0.crc.${_SANDBOX_ID}.instruqt.io
  new_window: true
```
